### ISSUE TITLE
Implementing OCM access for OC/NC ScienceMesh apps

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#4068]
I ran the `orro.sh` script from examples/sciencemesh (sciencemesh-testing branch of reva) and created a share from einstein@revaowncloud1.docker to marie@revaowncloud2.docker (token: `IA4Ho07wx0EJgnLrX1Gpy2yfjvf9cCt3`)

Now when I do:
```
curl -X PROPFIND https://revaowncloud1.docker/remote.php/dav/ocm/IA4Ho07wx0EJgnLrX1Gpy2yfjvf9cCt3/ 
```
(from inside the revaowncloud1.docker container) I see this error message in the logs:

```
023-07-14 15:13:52.507 WRN ../../reva/internal/grpc/services/storageregistry/storageregistry.go:123 > error: not found: storage provider not found for ref  pid=1260 pkg=rgrpc traceid=9ae59cb4a88f674945aae9c1a525ba47
```
What is going wrong there? Something misconfigured in the storage registry in https://github.com/cs3org/reva/blob/sciencemesh-testing/examples/sciencemesh/revad/sciencemesh1.toml maybe?

**Comment by gmgigi96** [comment]
Hi Michiel, in the configuration the line `"ocm" = {"address" = "your.revad.com:19001"}` is missing in `[grpc.services.storageregistry.drivers.static.rules]`.

**Comment by michielbdejong** [comment]
OK, can you fix it and test?

**Comment by michielbdejong** [comment]
This is the Reva config template for all ScienceMesh sites except CERN, if there is a line missing from it then none of the sites except CERN will work. It would be great if you could take over the maintenance of these toml templates from me!

**Comment by gmgigi96** [comment]
Michiel, these have been tested https://github.com/cs3org/reva/blob/master/examples/ocmd/server-1.toml
You can use this config, and replace the json drivers with your own `nextcloud` drivers.

**Comment by michielbdejong** [comment]
@gmgigi96 thanks, that is not a fix but it is helpful info so that others can fix it.

@glpatcern can you update the official templates for ScienceMesh using that hint?

**Comment by michielbdejong** [comment]
And @MahdiBaghbani can you assist him this week?

**Comment by MahdiBaghbani** [comment]
Hi, Yes of course.
We talked about the Reva mount -> compile -> mechanism on Friday over
Gitter, I think Giuseppe is ok with the approach and it’s not much annoying
like rebuilding the image again.

I went to test the orro scenario to find out about changes since the last
time I interacted with Sciencemesh.

We’ll be working on this issue in coming week!

**Comment by glpatcern** [comment]
> @glpatcern can you update the official templates for ScienceMesh using that hint?

The current state of the `sciencemesh-testing` branch does not allow that, for now I only updated the config with the missing bit but kept the three different configs. I also cherry-picked my PR with the HTTP logs. But the branch needs some care to be rebased in front of `master`.

**Comment by glpatcern** [comment]
An update with the current state of affairs.

I have cherry-picked a few commits from `master` into `sciencemesh-testing`, in particular removing `/ocs-provider` and adding http logging, on top of adding the necessary ocm-related config. The branch is currently failing several unit tests, and the problematic code has to be fixed prior to get it merged (and I expect those fixes will work towards getting a functioning MVP!).

Apart that, I have tested the `orro.sh` scenario as follows:
* created a share on the `einstein` side (ok)
* accepted it on the `marie` side (ok) (this instead failed if the `/ocs-provider` service is present!)
* accessed it on the `marie` side (failed)

The last step is as we know where things are yet to be fixed. I see the 404 error Michiel got:

```
2023-08-07 13:59:24.231 DBG ../../home/lopresti/dev/cs3/REVASM/internal/http/services/owncloud/ocdav/dav.go:232 > OCM user authenticated pid=839 pkg=rhttp token=6pGnTNShbXmaYJzIepg5mtTWzxTSJG1p traceid=a46bbe9501c00b0604ca406ba2f1f2af user={"display\_name":"marie","id":{"idp":"revaowncloud2.docker","opaque\_id":"marie","type":6},"opaque":{"map":{"ocm-share-role":{"decoder":"plain","value":"aW52YWxpZA=="}}}}
2023-08-07 13:59:24.358 WRN ../../home/lopresti/dev/cs3/REVASM/internal/http/interceptors/log/log.go:101 > processed http request host=172.20.0.10 method=PROPFIND pid=839 pkg=rhttp status=404 traceid=a46bbe9501c00b0604ca406ba2f1f2af uri=/remote.php/dav/ocm/
```

And the reason why the PROPFIND fails seems related to a failing call to `/index.php/apps/sciencemesh/~<token>/api/auth/Authenticate` on the `einstein` side:

```
2023-08-07 13:59:24.16 INF ../../home/lopresti/dev/cs3/REVASM/pkg/auth/manager/nextcloud/nextcloud.go:175 > Authenticate 6pGnTNShbXmaYJzIepg5mtTWzxTSJG1p {"clientID":"6pGnTNShbXmaYJzIepg5mtTWzxTSJG1p","clientSecret":""} pid=839 pkg=rgrpc traceid=8afb8aee75fc9195028979f0e771c554
2023-08-07 13:59:24.16 INF ../../home/lopresti/dev/cs3/REVASM/pkg/auth/manager/nextcloud/nextcloud.go:126 > am.do https://owncloud1.docker/index.php/apps/sciencemesh/~6pGnTNShbXmaYJzIepg5mtTWzxTSJG1p/api/auth/Authenticate {"clientID":"6pGnTNShbXmaYJzIepg5mtTWzxTSJG1p","clientSecret":""} shared-secret-1 pid=839 pkg=rgrpc traceid=8afb8aee75fc9195028979f0e771c554
2023-08-07 13:59:24.188 INF ../../home/lopresti/dev/cs3/REVASM/pkg/auth/manager/nextcloud/nextcloud.go:145 > am.do response 403 "User not found" pid=839 pkg=rgrpc traceid=8afb8aee75fc9195028979f0e771c554
2023-08-07 13:59:24.188 WRN ../../home/lopresti/dev/cs3/REVASM/internal/grpc/services/authprovider/authprovider.go:170 > error authenticating user error="authsvc: error in Authenticate: Unexpected response code from EFSS API: 403" pid=839 pkg=rgrpc traceid=8afb8aee75fc9195028979f0e771c554
```

@mahdi is going to look on the ScienceMesh app side what happens behind the failing call.

**Comment by glpatcern** [comment]
Further progress: with the patch below we were able to pass the auth step with @MahdiBaghbani. But now we're stuck at the storageprovider level. For that, a more significant refactoring is needed in the `RevaController.php` class.

Patch for the authentication:
```
diff --git a/lib/Controller/RevaController.php b/lib/Controller/RevaController.php
index 657f8c3..6f36bd4 100644
--- a/lib/Controller/RevaController.php
+++ b/lib/Controller/RevaController.php
@@ -374,6 +374,19 @@ class RevaController extends Controller {
                ];
        }

+       private function formatFederatedUser($username, $remote) {
+               return [
+                       "id" => [
+                               "idp" => $remote,
+                               "opaque_id" => $username,
+                       ],
+                       "display_name" => $username,   // FIXME: this comes in the OCM share payload
+                       "username" => $username,
+                       "email" => "unknown@unknown",  // FIXME: this comes in the OCM share payload
+                       "type" => 6,
+               ];
+       }
+
        /**
         * @PublicPage
         * @NoAdminRequired
@@ -385,7 +398,17 @@ class RevaController extends Controller {
                if ($this->userManager->userExists($userId)) {
                        $this->init($userId);
                } else {
-                       return new JSONResponse("User not found", Http::STATUS_FORBIDDEN);
+                       $share = $this->shareProvider->getSentShareByToken($userId);
+                       if ($share) {
+                               $sharedWith = explode("@", $share->getSharedWith());
+                               $result = [
+                                       "user" => $this->formatFederatedUser($sharedWith[0], $sharedWith[1]),
+                                       "scopes" => [],
+                               ];
+                               return new JSONResponse($result, Http::STATUS_OK);
+                       } else {
+                               return new JSONResponse("User not found", Http::STATUS_FORBIDDEN);
+                       }
                }
                $userId = $this->request->getParam("clientID");
                $password = $this->request->getParam("clientSecret");
@@ -393,7 +416,7 @@ class RevaController extends Controller {
                // Try e.g.:
                // curl -v -H 'Content-Type:application/json' -d'{"clientID":"einstein",clientSecret":"relativity"}' http://einstein:relativity@localhost/index.php/apps/sciencemesh/~einstein/api/auth/Authenticate

-    // Ref https://github.com/cs3org/reva/issues/2356
+               // Ref https://github.com/cs3org/reva/issues/2356
                if ($password == $this->config->getRevaLoopbackSecret()) {
                        $user = $this->userManager->get($userId);
                } else {
@@ -402,7 +425,7 @@ class RevaController extends Controller {
                if ($user) {
                        $result = [
                                "user" => $this->formatUser($user),
-                               "scopes" => [
+                               "scopes" => [   // FIXME this hardcoded value represents {"resource_id":{"storage_id":"storage-id","opaque_id":"opaque-id"},"path":"some/file/path.txt"} and is not needed
                                        "user" => [
                                                "resource" => [
                                                        "decoder" => "json",
```

**Comment by glpatcern** [comment]
With the help of @gmgigi96 we progressed quite a bit. The storage routing in Reva is now functional, see https://github.com/cs3org/reva/commit/f61ff090f4543597a371e5ebd0775b85b74b4ae9, but the SM app in ownCloud fails with:

```
[Wed Aug 09 10:03:27.011187 2023] [php7:notice] [pid 18] [client 172.20.0.11:45566] GetMD array (\n  'resource_id' => \n  array (\n    'storage_id' => 'nextcloud',\n    'opaque_id' => 'fileid-/einstein/files/SharedTomarie',\n  ),\n)
172.20.0.11 - - [09/Aug/2023:10:03:26 +0000] "POST /index.php/apps/sciencemesh/~nobody/api/ocm/GetSentShareByToken HTTP/1.1" 200 3220 "-" "Go-http-client/1.1"
172.20.0.11 - - [09/Aug/2023:10:03:26 +0000] "POST /index.php/apps/sciencemesh/~nobody/api/ocm/GetSentShareByToken HTTP/1.1" 200 1636 "-" "Go-http-client/1.1"
172.20.0.11 - - [09/Aug/2023:10:03:26 +0000] "POST /index.php/apps/sciencemesh/~unauthenticated/api/user/GetUser HTTP/1.1" 200 1178 "-" "Go-http-client/1.1"
172.20.0.11 - - [09/Aug/2023:10:03:26 +0000] "POST /index.php/apps/sciencemesh/~einstein/api/user/GetUserByClaim HTTP/1.1" 200 1168 "-" "Go-http-client/1.1"
172.20.0.11 - - [09/Aug/2023:10:03:26 +0000] "POST /index.php/apps/sciencemesh/~einstein/api/storage/CreateHome HTTP/1.1" 200 1030 "-" "Go-http-client/1.1"
172.20.0.11 - - [09/Aug/2023:10:03:26 +0000] "POST /index.php/apps/sciencemesh/~einstein/api/storage/GetMD HTTP/1.1" 500 9405 "-" "Go-http-client/1.1"
{"reqId":"U3BRHeNlkmGg8uQIoEEn","level":3,"time":"2023-08-09T10:03:27+00:00","remoteAddr":"172.20.0.11","user":"--","app":"index","method":"POST","url":"\/index.php\/apps\/sciencemesh\/~einstein\/api\/storage\/GetMD","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"ref not understood!\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\ScienceMesh\\\\Controller\\\\RevaController->GetMD()\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#6 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/sciencemesh\\\/lib\\\/Controller\\\/RevaController.php\",\"Line\":631}"}
```

Off to @MahdiBaghbani to continue

**Comment by glpatcern** [comment]
This was fixed with the latest patches by @MahdiBaghbani, and `PROPFIND` requests via Reva work now, meaning that Reva is a priori able to serve files from the local OC/NC to remote users. E.g.:

```
root@d212263336ae:/etc/revad# curl -X  PROPFIND 'https://revaowncloud1.docker/remote.php/dav/ocm/5FHHoEGbQ7wKpM1rHM1R0paZRKxDiKcv/testfile'
<?xml version="1.0" encoding="utf-8"?><d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/dav/ocm/5FHHoEGbQ7wKpM1rHM1R0paZRKxDiKcv/testfile</d:href><d:propstat><d:prop><oc:id>nextcloud!fileid-/home/SharedTomarie/testfile</oc:id>[...]</d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

This hopefully closes this issue on the reva side, but something else needs to be fixed for the full workflow to work: see https://github.com/sciencemesh/nc-sciencemesh/issues/32, https://github.com/sciencemesh/nc-sciencemesh/issues/33, and https://github.com/sciencemesh/nc-sciencemesh/issues/34 for the remaining issues.
