### ISSUE TITLE
failing github.com/cs3org/reva/v2/pkg/appctx test

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#4126]
`make all` fails reliably with
```
--- FAIL: TestGetKeyValues (0.00s)
    --- FAIL: TestGetKeyValues/Background_context (0.00s)
panic: reflect: call of reflect.Value.Elem on struct Value [recovered]
        panic: reflect: call of reflect.Value.Elem on struct Value

goroutine 22 [running]:
testing.tRunner.func1.2({0xca3cc0, 0xc000122a68})
        /usr/lib/go/src/testing/testing.go:1545 +0x366
testing.tRunner.func1()
        /usr/lib/go/src/testing/testing.go:1548 +0x630
panic({0xca3cc0?, 0xc000122a68?})
        /usr/lib/go/src/runtime/panic.go:920 +0x270
reflect.Value.Elem({0xd1aa00?, 0x12cd440?, 0xf6c80e?})
        /usr/lib/go/src/reflect/value.go:1271 +0x455
github.com/cs3org/reva/v2/pkg/appctx.getKeyValue({0xd1aa00, 0x12cd440}, 0x4ad2d9?)
        /home/jfd/Repositories/reva/pkg/appctx/ctxmap.go:44 +0x158
github.com/cs3org/reva/v2/pkg/appctx.GetKeyValuesFromCtx(...)
        /home/jfd/Repositories/reva/pkg/appctx/ctxmap.go:39
github.com/cs3org/reva/v2/pkg/appctx.TestGetKeyValues.func1(0x0?)
        /home/jfd/Repositories/reva/pkg/appctx/ctxmap_test.go:70 +0xda
testing.tRunner(0xc00048c820, 0xc000349cf0)
        /usr/lib/go/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 21
        /usr/lib/go/src/testing/testing.go:1648 +0x82b
FAIL    github.com/cs3org/reva/v2/pkg/appctx    0.031s
```

with go 1.21.0 ... hmmm

**Comment by dragonchaser** [comment]
Can reproduce

**Comment by butonic** [comment]
see https://tip.golang.org/doc/go1.21#reflect

**Comment by dragonchaser** [comment]
fix in https://github.com/cs3org/reva/pull/4194

**Comment by butonic** [comment]
fixed with https://github.com/cs3org/reva/pull/4194
