### ISSUE TITLE
concurrent access to client pool maps is unsafe

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#908]
@labkode I can aswer this question
https://github.com/cs3org/reva/blob/bfff93db216c1991339f17fa350f3c0a6bbce342/pkg/rgrpc/todo/pool/pool.go#L42-L57

with a definitive [no from the ci](https://cloud.drone.io/owncloud/ocis/758/4/7):
```

3783 | 2020-06-30T06:22:01Z INF core access token generated pkg=rhttp service=reva traceid=28300298520e48d620290536e9c69c96
--
3784 | fatal error: concurrent map writes
3785 |  
3786 | goroutine 1224 [running]:
3787 | runtime.throw(0x385b645, 0x15)
3788 | /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00058cff0 sp=0xc00058cfc0 pc=0x138e122
3789 | runtime.mapassign_faststr(0x32e6c00, 0xc000194c30, 0x384a840, 0xe, 0x0)
3790 | /usr/local/go/src/runtime/map_faststr.go:211 +0x417 fp=0xc00058d058 sp=0xc00058cff0 pc=0x1371f87
3791 | github.com/cs3org/reva/pkg/rgrpc/todo/pool.GetUserShareProviderClient(0x384a840, 0xe, 0x15ebbdc, 0xc001dc90e0, 0x530bd00, 0xc000d7f100)
3792 | /srv/app/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200629131207-04298ea1c088/pkg/rgrpc/todo/pool/pool.go:161 +0xfc fp=0xc00058d0a8 sp=0xc00058d058 pc=0x28498cc
3793 | github.com/cs3org/reva/internal/grpc/services/gateway.(*svc).ListReceivedShares(0xc000cd41e0, 0x3d62980, 0xc0023d1bf0, 0xc0023d18c0, 0xc000cd41e0, 0x1, 0xc001d97808)
3794 | /srv/app/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200629131207-04298ea1c088/internal/grpc/services/gateway/usershareprovider.go:234 +0x3f fp=0xc00058d110 sp=0xc00058d0a8 pc=0x2862baf
3795 | github.com/cs3org/go-cs3apis/cs3/gateway/v1beta1._GatewayAPI_ListReceivedShares_Handler.func1(0x3d62980, 0xc0023d1bf0, 0x364e0e0, 0xc0023d18c0, 0x32, 0x0, 0x0, 0x3d62980)
3796 | /srv/app/pkg/mod/github.com/cs3org/go-cs3apis@v0.0.0-20200625121012-96e791152b14/cs3/gateway/v1beta1/gateway_api.pb.go:2623 +0x89 fp=0xc00058d158 sp=0xc00058d110 pc=0x27a69a9
3797 | github.com/cs3org/reva/internal/grpc/interceptors/auth.NewUnary.func1(0x3d62980, 0xc0023d1aa0, 0x364e0e0, 0xc0023d18c0, 0xc001bcfae0, 0xc001bcfb00, 0x0, 0x0, 0x0, 0x0)
```

**Comment by butonic** [comment]
@refs has written some concurrency safe stuff for the json share provider IIRC?

**Comment by refs** [comment]
A lock on the `pool` package should orchestrate this. On the other hand if you want to go fancy, a [sync.Map](https://golang.org/pkg/sync/#Map) can be also used, which would fit this use case:

>  The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.
