### ISSUE TITLE
File don't move to correct path after upload when TUS is disabled

### ISSUE THREAD

**Issue by JarCz** [cs3org/reva#910]
Problem:
When i'm test wopi server with config from: https://github.com/cs3org/wopiserver
and test with examples:
- https://github.com/cs3org/wopiserver/tree/master/test
- https://github.com/JarCz/cs3api4lab/tree/cs3_api/cs3api4lab/cs3api

file is upload, but don't move to correct path in filesystem.

Steps to reproduce:
1. Clone wopi server: https://github.com/cs3org/wopiserver
2. Modify reva config in: reva/examples/ocmd/ocmd-server-1.toml
Replace data provide section to:

```
[http.services.dataprovider]
driver = "local"
temp_folder = "/var/tmp/"
disable_tus = true
```
3. Run reva demon with: 
```
../../cmd/revad/revad -c ocmd-server-1.toml 
```

4. Run single test from wopi server:

```
cd wopiserver/test/
python3 test_storageiface.py TestStorage.test_write_remove
```

Result:
Test not passed (OSError: file not found), but 
1. Open in browser url from riva log "http://localhost:19001/data/{file_id}"
2. Log with: einstein/relativity
3. You see correct upload data in temporary url
4. Check file in local file system:

```
$ cd /var/tmp/reva/data/
$ less {file_id}
```
5. File is uploaded correctly and can read from local file system

Example log from riva demon:
```
10:29AM DBG home/dev/work/reva/pkg/storage/utils/localfs/upload.go:124 > localfs: NewUpload info={"ID":"","IsFinal":false,"IsPartial":false,"MetaData":{"dir":"/","filename":"testwrite"},"Offset":0,"PartialUploads":null,"Size":0,"SizeIsDeferred":false,"Storage":null} pid=21518 pkg=rgrpc traceid=c75e75bf6a3ba0c230c27716a754f5ca
10:29AM DBG home/dev/work/reva/pkg/storage/utils/localfs/upload.go:140 > localfs: resolved filename info={"ID":"","IsFinal":false,"IsPartial":false,"MetaData":{"dir":"/","filename":"testwrite"},"Offset":0,"PartialUploads":null,"Size":0,"SizeIsDeferred":false,"Storage":null} pid=21518 pkg=rgrpc traceid=c75e75bf6a3ba0c230c27716a754f5ca
10:29AM INF home/dev/work/reva/internal/grpc/services/storageprovider/storageprovider.go:305 > file upload data-server=http://localhost:19001/data/25128cba-e31c-4811-86a3-7c18a1c796f4 fn=/testwrite pid=21518 pkg=rgrpc traceid=c75e75bf6a3ba0c230c27716a754f5ca xs="map[md5:100 unset:1000]"
10:29AM INF home/dev/work/reva/internal/grpc/interceptors/log/log.go:69 > unary code=OK end="30/Jun/2020:10:29:19 +0200" from=tcp://127.0.0.1:38886 pid=21518 pkg=rgrpc start="30/Jun/2020:10:29:19 +0200" time_ns=500903 traceid=c75e75bf6a3ba0c230c27716a754f5ca uri=/cs3.storage.provider.v1beta1.ProviderAPI/InitiateFileUpload user-agent=grpc-go/1.26.0
10:29AM INF home/dev/work/reva/internal/grpc/services/gateway/storageprovider.go:370 > upload is routed directly to data server - skiping datagateway pid=21518 pkg=rgrpc traceid=c75e75bf6a3ba0c230c27716a754f5ca
10:29AM INF home/dev/work/reva/internal/grpc/interceptors/log/log.go:69 > unary code=OK end="30/Jun/2020:10:29:19 +0200" from=tcp://[::1]:52574 pid=21518 pkg=rgrpc start="30/Jun/2020:10:29:19 +0200" time_ns=1347475 traceid=c75e75bf6a3ba0c230c27716a754f5ca uri=/cs3.gateway.v1beta1.GatewayAPI/InitiateFileUpload user-agent="grpc-python/1.30.0 grpc-c/10.0.0 (manylinux; chttp2)"
```

**Comment by ishank011** [comment]
You need to add the `disable_tus` option in `storageprovider` as well.

```
[grpc.services.storageprovider]
disable_tus = true
```

**Comment by JarCz** [comment]
Don't work.
still the same effect - file not found:

Fresh reva clone:
commit 39a90d43156680adda3f15301aa9c711e7484385 (HEAD -> master, origin/master, origin/HEAD)
Date:   Tue Jun 30 09:59:23 2020 +0200

with config:

```
[grpc.services.storageprovider]
driver = "localhome"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
expose_data_server = true
data_server_url = "http://localhost:19001/data"
enable_home_creation = true
disable_tus = true

...

[http.services.dataprovider]
driver = "local"
temp_folder = "/var/tmp/"
disable_tus = true
```

```
$ python3 test_storageiface.py TestStorage.test_write_remove
======================================================================
ERROR: test_write_remove (__main__.TestStorage)
Test write and removal of a file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_storageiface.py", line 123, in test_write_remove
    statInfo = self.storage.stat(self.endpoint, '/testwrite', self.userid)
  File "../src/cs3iface.py", line 89, in stat
    raise IOError(statInfo.status.message)
OSError: file not found

----------------------------------------------------------------------
Ran 1 test in 0.008s

FAILED (errors=1)
```

**Comment by ishank011** [comment]
You're using the local driver in dataprovider and localhome in storageprovider. Both should use localhome.

Which config file are you even using? ocmd-server-1.toml looks different.

**Comment by JarCz** [comment]
Config  ocmd-server-1.toml from https://github.com/cs3org/reva/blob/master/examples/ocmd/ocmd-server-1.toml
and changes from https://github.com/cs3org/wopiserver section "Test against a Reva endpoint".

**Comment by JarCz** [comment]
Test passed when change config to:
```
[http.services.dataprovider]
driver = "localhome"
temp_folder = "/var/tmp/"
disable_tus = true
```
